name: Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - run: sudo apt-get update && sudo apt-get install fortune -y
  
    - uses: actions/checkout@v2
    - name: Setup nodejs
      uses: actions/setup-node@v1
    - run: npm ci
    - run: npm test
